layout_spectrum: 0.2526882
color:
  saturation: 0.2939068
  brandStrength: 0.9305431
  lightness: 0.218638
  rhythmicContrast: 0.2329749
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
typography_spectrum: 0.218638
name: LAS
